name: "Update Preview App"
on:
  pull_request:
    types: [synchronize]

env:
  PROJECT: ${{ github.event.repository.name }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  PR_NUMBER: ${{ github.event.number }}
  DOMAIN: feedback-interface.icyntkt.xyz # OurApp Subdomain
  AWS_REGION: us-east-2 # REGION
  ECR_REPOSITORY: team5-client-app-test3 # IMAGE_REPOSITORY
  ECS_CLUSTER: team5-client-app3-cluster # CLUSTER_NAME
  PORT: 5173 # PORT
  ROLE_ARN: arn:aws:iam::126480444030:role/ecsTaskExecutionRole # EXECUTION_ROLE_ARN
  LB_NAME: team5-load-balancer # DEFAULT_LB
  SUBNET_NAME: subnet-01cef9a94723b1c34 # DEFAULT_SUBNET
  SG_NAME: sg-0dd59509b20ad0cfd # SECURITY_GROUP

jobs:
  teardown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: set ECR Registry Environment Variable
        run: |
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Delete App on Amazon ECS
        id: delete-preview
        uses: ./.github/actions/delete-preview

      - name: Deploy Updated App to Amazon ECS
        id: deploy-app
        uses: ./.github/actions/deploy-preview

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Comment Status as Updated
        uses: hasura/comment-progress@v2.3.0
        with:
          id: update-comment
          github-token: ${{ steps.app-token.outputs.token }}
          repository: ${{ github.repository }}
          number: ${{ env.PR_NUMBER }}
          message: "| Status | Message |\n|--------|-------|\n| \U00002757 | Your preview has been updated with the lastest commit. Visit your super cool amazing preview app here ${{ steps.deploy-app.outputs.url }} |"
          append: false
